In [1]:
import pandas as pd

In [2]:
pd.__version__

'2.3.3'

In [4]:
df = pd.read_csv("Customer_Churn_Analysis.csv")

In [5]:
df.to_csv("Customer_Churn_Analysis.csv",index=False)

In [6]:
df.head()

,Customer_ID,Contract_ID,Payment_ID,Gender,Age,Tenure_Months,Monthly_Charges,Total_Charges,Internet_Service,Customer_Support_Calls,Senior_Citizen,Partner,Dependents,Churn
0,CUST00001,CON00001,PAY00001,Female,29,58,95.71,5551.18,Fiber Optic,6,No,Yes,No,Yes
1,CUST00002,CON00002,PAY00002,Female,56,69,99.46,6862.74,Fiber Optic,2,Yes,Yes,Yes,Yes
2,CUST00003,CON00003,PAY00003,Female,27,39,27.99,1091.61,NaN,3,No,No,No,Yes
3,CUST00004,CON00004,PAY00004,Male,24,38,48.59,1846.42,Fiber Optic,1,Yes,No,No,No
4,CUST00005,CON00005,PAY00005,Male,73,44,63.18,2779.92,Cable,6,No,Yes,No,Yes

df.tail()

In [7]:
df.shape

(8000, 14)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             8000 non-null   object
 1   Contract_ID             8000 non-null   object
 2   Payment_ID              8000 non-null   object
 3   Gender                  8000 non-null   object
 4   Age                     8000 non-null   int64
 5   Tenure_Months           8000 non-null   int64
 6   Monthly_Charges         8000 non-null   float64
 7   Total_Charges           8000 non-null   float64
 8   Internet_Service        5951 non-null   object
 9   Customer_Support_Calls  8000 non-null   int64
 10  Senior_Citizen          8000 non-null   object
 11  Partner                 8000 non-null   object
 12  Dependents              8000 non-null   object
 13  Churn                   8000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 875.1+ KB

In [9]:
df.describe()

,Age,Tenure_Months,Monthly_Charges,Total_Charges,Customer_Support_Calls
count,8000.000000,8000.000000,8000.000000,8000.000000,8000.000000
mean,47.846375,36.333500,62.704521,2294.740500,3.684375
std,18.115368,20.617988,24.721418,1677.019644,2.607509
min,18.000000,1.000000,24.990000,25.120000,0.000000
25%,31.000000,21.000000,45.560000,1048.410000,1.000000
50%,51.000000,36.000000,59.970000,1905.180000,4.000000
75%,64.000000,52.000000,81.792500,3167.672500,6.000000
max,77.000000,72.000000,104.980000,7529.760000,9.000000

In [10]:
df.describe(include="object")

,Customer_ID,Contract_ID,Payment_ID,Gender,Internet_Service,Senior_Citizen,Partner,Dependents,Churn
count,8000,8000,8000,8000,5951,8000,8000,8000,8000
unique,8000,8000,8000,2,3,2,2,2,2
top,CUST00001,CON00001,PAY00001,Female,Cable,No,No,Yes,Yes
freq,1,1,1,4196,2241,4525,4346,4300,4145

In [11]:
df.columns

Index(['Customer_ID', 'Contract_ID', 'Payment_ID', 'Gender', 'Age',
       'Tenure_Months', 'Monthly_Charges', 'Total_Charges', 'Internet_Service',
       'Customer_Support_Calls', 'Senior_Citizen', 'Partner', 'Dependents',
       'Churn'],
      dtype='object')

In [13]:
df = df.drop(columns=["Unnamed: 0"],axis = 1)

KeyError: "['Unnamed: 0'] not found in axis"

In [55]:
df.dtypes

Customer_ID                object
Contract_ID                object
Payment_ID                 object
Gender                     object
Age                         int64
Tenure_Months               int64
Monthly_Charges           float64
Total_Charges             float64
Internet_Service           object
Customer_Support_Calls      int64
Senior_Citizen             object
Partner                    object
Dependents                 object
Churn                      object
dtype: object

In [14]:
df.isnull().sum()

Customer_ID                  0
Contract_ID                  0
Payment_ID                   0
Gender                       0
Age                          0
Tenure_Months                0
Monthly_Charges              0
Total_Charges                0
Internet_Service          2049
Customer_Support_Calls       0
Senior_Citizen               0
Partner                      0
Dependents                   0
Churn                        0
dtype: int64

In [17]:
df["Internet_Service"] = df["Internet_Service"].fillna(df["Internet_Service"].mode()[0])

In [18]:
df["Internet_Service"].isna().sum()

np.int64(0)

In [19]:
df["Internet_Service"].value_counts()

Internet_Service
Cable          4290
Fiber Optic    2070
DSL            1640
Name: count, dtype: int64

In [33]:
df.nunique()

Customer_ID               8000
Contract_ID               8000
Payment_ID                8000
Gender                       2
Age                         60
Tenure_Months               72
Monthly_Charges           3973
Total_Charges             7698
Internet_Service             3
Customer_Support_Calls      10
Senior_Citizen               2
Partner                      2
Dependents                   2
Churn                        2
dtype: int64

In [34]:
df['Gender'].unique()

array(['Female', 'Male'], dtype=object)

In [30]:
df.duplicated().sum()

np.int64(0)

In [58]:
df["Gender"].value_counts()

Gender
Female    4196
Male      3804
Name: count, dtype: int64

In [60]:
df["Internet_Service"].value_counts()

Internet_Service
Cable          4290
Fiber Optic    2070
DSL            1640
Name: count, dtype: int64

In [35]:
df['Churn'].value_counts()

Churn
Yes    4145
No     3855
Name: count, dtype: int64

In [36]:
df.select_dtypes(include='number').columns

Index(['Age', 'Tenure_Months', 'Monthly_Charges', 'Total_Charges',
       'Customer_Support_Calls'],
      dtype='object')

In [37]:
df['Churn'].value_counts(normalize=True)*100  ##churn percentage

Churn
Yes    51.8125
No     48.1875
Name: proportion, dtype: float64

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer_ID             8000 non-null   object
 1   Contract_ID             8000 non-null   object
 2   Payment_ID              8000 non-null   object
 3   Gender                  8000 non-null   object
 4   Age                     8000 non-null   int64
 5   Tenure_Months           8000 non-null   int64
 6   Monthly_Charges         8000 non-null   float64
 7   Total_Charges           8000 non-null   float64
 8   Internet_Service        5951 non-null   object
 9   Customer_Support_Calls  8000 non-null   int64
 10  Senior_Citizen          8000 non-null   object
 11  Partner                 8000 non-null   object
 12  Dependents              8000 non-null   object
 13  Churn                   8000 non-null   object
dtypes: float64(2), int64(3), object(9)
memory usage: 875.1+ KB

In [63]:
df.head()

,Customer_ID,Contract_ID,Payment_ID,Gender,Age,Tenure_Months,Monthly_Charges,Total_Charges,Internet_Service,Customer_Support_Calls,Senior_Citizen,Partner,Dependents,Churn
0,CUST00001,CON00001,PAY00001,Female,29,58,95.71,5551.18,Fiber Optic,6,No,Yes,No,Yes
1,CUST00002,CON00002,PAY00002,Female,56,69,99.46,6862.74,Fiber Optic,2,Yes,Yes,Yes,Yes
2,CUST00003,CON00003,PAY00003,Female,27,39,27.99,1091.61,Cable,3,No,No,No,Yes
3,CUST00004,CON00004,PAY00004,Male,24,38,48.59,1846.42,Fiber Optic,1,Yes,No,No,No
4,CUST00005,CON00005,PAY00005,Male,73,44,63.18,2779.92,Cable,6,No,Yes,No,Yes

In [20]:
df.to_csv("Cleaned_Customer_Churn_Analysis.csv", index = False)